"use client";

import {useEffect,useState} from "react";
import {ArrowRight,ArrowUpRight,Eye,Heart,MessageCircle,Play,Newspaper,Camera,Video,MapPin} from "@/lib/icons";
import MediaPlayer from "./media-player";
import SiteShell,{api,useSession} from "./site-shell";
import {Button} from "@/components/ui/button";
import {type Post,kindLabels,dateLabel} from "@/lib/models";
export default function MediaHome({mode}:{mode:string}){return <SiteShell><HomeContent mode={mode}/></SiteShell>}
function HomeContent({mode}:{mode:string}){const {user,ready,error:sessionError,retry}=useSession();const[posts,setPosts]=useState<Post[]>([]);const[page,setPage]=useState(0);const[more,setMore]=useState(false);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[needsLogin,setNeedsLogin]=useState(false);const[attempt,setAttempt]=useState(0);
useEffect(()=>{if(!ready)return;let active=true;setLoading(true);api(`posts?mode=${mode}&page=${page}`).then(d=>{if(active){setPosts(p=>page?[...p,...d.posts]:d.posts);setMore(d.hasMore);setError("");setNeedsLogin(false)}}).catch(e=>{if(active){setError(e.message);setNeedsLogin(e.status===401)}}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[ready,mode,page,attempt]);
const titles:Record<string,[string,string,string]>={all:["ताजा अपडेट","Latest from our community","प्रसौनी र वरपरका कथा, सूचना र आवाजहरू।"],gallery:["तस्बिरमा हाम्रो समुदाय","The gallery","हाम्रो ठाउँ, हाम्रा मानिस र सम्झनाका पलहरू।"],videos:["हेर्नुहोस्, सुन्नुहोस्, जोडिनुहोस्","Video stories","Facebook, TikTok र प्रसौनी Voice का भिडियोहरू।"],blog:["लेख र विचार","Stories & perspectives","स्थानीय विषयमा अनुभव, विचार र गहिरो संवाद।"]};const title=titles[mode]||titles.all;
return <main>{mode==="all"?<><div className="edition-strip wrap"><span><i/> COMMUNITY EDITION</span><span>प्रसौनी गाउँपालिका, बारा</span><span className="edition-country">NEPAL / नेपाल</span></div><section className="hero wrap"><div className="hero-copy"><span className="eyebrow"><span className="red-line"/> तपाईंको समुदाय, तपाईंको मञ्च</span><h1>आफ्नो ठाउँ।<br/>आफ्नो <em>आवाज।</em></h1><p>प्रसौनीका कथा, जनसरोकारका विषय र समुदायका पलहरू।<br/><span>Local stories. Real conversations. One community.</span></p><div className="hero-actions"><a href="#feed" className="btn">अपडेट हेर्नुहोस् <ArrowRight size={18}/></a><a href="/videos" className="text-link"><span className="play-ring"><Play size={12} fill="currentColor"/></span> Watch videos</a></div><div className="hero-location"><MapPin size={16}/><span>प्रसौनीदेखि संसारसम्म <b>From Prasauni, to the world.</b></span></div></div><div className="hero-image"><img src="/community-cover.jpg" alt="Nepali flag and heritage architecture from Prasauni Voice’s social cover"/><div className="photo-shade"/><span className="photo-label">हाम्रो पहिचान / OUR IDENTITY</span><div className="photo-caption"><span>हामीलाई जोड्ने कथा</span><h2>जरा स्थानीय।<br/>आवाज सबैको।</h2><a href="https://www.facebook.com/prasaunivoice" target="_blank" rel="noreferrer" aria-label="Visit Prasauni Voice Facebook"><ArrowUpRight size={25}/></a></div><small className="photo-credit">Prasauni Voice · Social cover</small></div></section><div className="values-strip wrap"><span><Newspaper size={19}/><b>स्थानीय विषय</b><small>Closer to home</small></span><span><Camera size={19}/><b>समुदायका पलहरू</b><small>Life in pictures</small></span><span><MessageCircle size={19}/><b>तपाईंको विचार</b><small>Every voice matters</small></span></div></>:<section className="section-banner wrap"><span className="eyebrow">PRASAUNI VOICE / {title[1].toUpperCase()}</span><h1>{title[0]}</h1><p>{title[2]}</p></section>}
<div className={`wrap content-layout ${mode!=="all"?"single-layout":""}`}><section id="feed" className="feed"><div className="section-heading"><div><span className="eyebrow">{title[1]}</span><h2>{mode==="all"?title[0]:mode==="gallery"?"फोटो संग्रह":mode==="videos"?"भिडियो संग्रह":"पछिल्ला लेख"}</h2></div><span className="section-rule"/><span className="edition-note">PRASAUNI VOICE</span></div>{sessionError||error?<div className="empty-state"><Newspaper size={32}/><h3>{needsLogin?"पूरा पोस्ट हेर्न Login गर्नुहोस्":"अपडेट लोड हुन सकेन"}</h3><p role="alert">{sessionError||error}</p>{needsLogin?<div className="preview-actions"><a href={"/login?next="+encodeURIComponent(mode==="all"?"/":"/"+(mode==="gallery"?"gallery":mode==="videos"?"videos":"blog"))} className="btn">Login गरेर पढ्नुहोस्</a><form method="post" action="/api/preview"><Button variant="outline" type="submit">फेरि ३० सेकेन्ड हेर्नुहोस्</Button></form></div>:<Button variant="outline" onClick={()=>sessionError?retry():setAttempt(n=>n+1)}>Try again</Button>}</div>:loading&&!posts.length?<div className="empty-state" role="status"><span className="loading-dot"/><p>अपडेट लोड हुँदैछ…</p></div>:!posts.length?<div className="empty-state"><div className="empty-icon">{mode==="gallery"?<Camera/>:mode==="videos"?<Video/>:<Newspaper/>}</div><span className="eyebrow">A NEW CHAPTER</span><h3>हाम्रो डिजिटल चौतारीमा स्वागत छ।</h3><p>{mode==="gallery"?"नयाँ तस्बिरहरू यहाँ देखिनेछन्।":mode==="videos"?"नयाँ भिडियोहरू यहाँ देखिनेछन्।":"नयाँ पोस्ट प्रकाशित भएपछि यहाँ देखिनेछन्।"}<br/>Until then, connect with us on Facebook and TikTok.</p>{user?.admin?<a href="/admin" className="btn">पहिलो पोस्ट थप्नुहोस् <ArrowRight size={17}/></a>:<a href="https://www.facebook.com/prasaunivoice" target="_blank" rel="noreferrer" className="text-link">Visit our Facebook <ArrowUpRight size={17}/></a>}</div>:<><div className={mode==="gallery"?"gallery-grid":"post-grid"}>{posts.map(p=><PostCard key={p.id} post={p} inline={mode==="videos"||mode==="gallery"}/>)}</div>{more&&<Button variant="outline" className="load-more" disabled={loading} onClick={()=>setPage(p=>p+1)}>{loading?"Loading…":"थप हेर्नुहोस् · Load more"}</Button>}</>}
</section>{mode==="all"&&<aside className="community-sidebar"><section className="community-card"><span className="eyebrow">THE CONVERSATION CONTINUES</span><h3>तपाईंको आवाजले<br/>फरक पार्छ।</h3><p>हेर्नुहोस्, मन पराउनुहोस् र आफ्ना विचार राख्नुहोस्।</p><a href={user?"/blog":"/login"} className="sidebar-link">{user?"समुदायका लेख":"समुदायमा जोडिनुहोस्"}<ArrowUpRight size={21}/></a><div className="community-card-bottom"><span>PV</span><span>प्रसौनी Voice<br/><small>आफ्नो समुदायसँग नजिक</small></span></div></section><section className="social-sidebar"><h3>हामी सामाजिक सञ्जालमा</h3><a href="https://www.facebook.com/prasaunivoice" target="_blank" rel="noreferrer"><span className="social-icon facebook"><b aria-hidden="true">f</b></span><span><b>Facebook</b><small>@prasaunivoice</small></span><ArrowUpRight size={18}/></a><a href="https://www.tiktok.com/@prasaunivoice" target="_blank" rel="noreferrer"><span className="social-icon tiktok">♪</span><span><b>TikTok</b><small>@prasaunivoice</small></span><ArrowUpRight size={18}/></a></section><div className="editorial-note"><span>हाम्रो प्रतिबद्धता</span><p>तथ्यमा आधारित संवाद।<br/>सम्मानपूर्ण सहभागिता।<br/>समुदायको साझा आवाज।</p><a href="/privacy">Community guidelines ↗</a></div></aside>}</div></main>}
function PostCard({post:p,inline=false}:{post:Post;inline?:boolean}){return <article className="post-card">{inline&&(p.media_url||p.source_url)?<MediaPlayer post={p} autoplay/>:<a href={`/post/${p.id}`} className="post-art" aria-label={p.title}>{p.media_url&&p.kind!=="video"?<img src={p.media_url} alt={p.title} loading="lazy"/>:<div className={`post-type-art ${p.kind}`}><span>PRASAUNI VOICE</span>{["video","tiktok"].includes(p.kind)?<Play size={32}/>:p.kind==="facebook"?<b aria-hidden="true" className="text-4xl">f</b>:<Newspaper size={32}/>}<b>{kindLabels[p.kind]}</b></div>}<span className="post-category">{p.category}</span></a>}<div className="post-card-body"><div className="post-meta">{kindLabels[p.kind]} <span>·</span> {dateLabel(p.created_at)}</div><a href={`/post/${p.id}`}><h3>{p.title}</h3></a>{p.excerpt&&<p>{p.excerpt}</p>}<div className="post-stats"><span><Eye size={15}/>{p.views}</span><span><Heart size={15}/>{p.likes}</span><span><MessageCircle size={15}/>{p.comments}</span><a href={`/post/${p.id}`} aria-label={`Read ${p.title}`}><ArrowUpRight size={19}/></a></div></div></article>}
