"use client";

import {useCallback,useEffect,useState} from "react";
import {ArrowLeft,ArrowUpRight,Heart,Eye,MessageCircle,Send,Share2} from "@/lib/icons";
import MediaPlayer from "./media-player";
import SiteShell,{api,useSession} from "./site-shell";
import {Button} from "@/components/ui/button";
import {Textarea} from "@/components/ui/textarea";
import {type Post,type Comment,dateLabel,kindLabels} from "@/lib/models";
export default function PostDetail({id}:{id:string}){return <SiteShell><Detail id={id}/></SiteShell>}
function Detail({id}:{id:string}){const{user,ready,error:sessionError}=useSession();const[post,setPost]=useState<Post|null>(null);const[comments,setComments]=useState<Comment[]>([]);const[error,setError]=useState("");const[needsLogin,setNeedsLogin]=useState(false);const[message,setMessage]=useState("");const[body,setBody]=useState("");const[busy,setBusy]=useState(false);const[likeBusy,setLikeBusy]=useState(false);
const load=useCallback(async()=>{try{const d=await api("posts/"+id);setPost(d.post);setComments(d.comments);setError("");setNeedsLogin(false)}catch(e){setError((e as Error).message);setNeedsLogin((e as Error&{status:number}).status===401)}},[id]);
useEffect(()=>{if(ready){load();api(`posts/${id}/view`,{method:"POST"}).catch(()=>{})}},[ready,id,load]);
async function like(){if(!user){location.assign("/login?next=/post/"+id);return}if(!post)return;setLikeBusy(true);try{const d=await api(`posts/${id}/like`,{method:"PUT",body:JSON.stringify({liked:!post.liked})});setPost({...post,...d})}catch(e){setMessage((e as Error).message)}finally{setLikeBusy(false)}}
async function comment(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");try{const d=await api(`posts/${id}/comment`,{method:"POST",body:JSON.stringify({body})});setComments(c=>[d.comment,...c]);setBody("");setPost(p=>p?{...p,comments:p.comments+1}:p)}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
async function share(){try{await navigator.clipboard.writeText(location.href);setMessage("Link copied · लिंक कपी भयो")}catch{setMessage("Copy the link from your browser’s address bar.")}}
return <main className="detail wrap"><a href="/" className="back-link"><ArrowLeft size={16}/> सबै अपडेट</a>{error||sessionError?<div className="empty-state"><h2>पोस्ट खोल्न सकिएन</h2><p role="alert">{error||sessionError}</p>{needsLogin?<a className="btn" href={"/login?next=/post/"+id}>Login to read this post</a>:<Button onClick={load} variant="outline">Try again</Button>}</div>:!post?<div className="empty-state" role="status">पोस्ट लोड हुँदैछ…</div>:<article><header className="article-header"><span className="eyebrow">{post.category} / {kindLabels[post.kind]}</span><h1>{post.title}</h1>{post.excerpt&&<p>{post.excerpt}</p>}<div className="article-byline"><span className="mini-logo">PV</span><div><b>Prasauni Voice</b><span>{dateLabel(post.created_at)} {post.status==="draft"?"· Draft — only visible to admin":""}</span></div><span className="article-views"><Eye size={16}/>{post.views} views</span></div></header>{(post.media_url||post.source_url)&&<MediaPlayer post={post} autoplay/>}{post.body&&<div className="article-body">{post.body.split(/\n\s*\n/).map((p,i)=><p key={i}>{p}</p>)}</div>}<div className="engagement"><Button variant={post.liked?"default":"outline"} onClick={like} disabled={likeBusy}><Heart size={18} fill={post.liked?"currentColor":"none"}/>{post.likes} · {post.liked?"मन पर्यो":"Like"}</Button><span><MessageCircle size={18}/>{post.comments} comments</span><Button variant="ghost" onClick={share}><Share2 size={18}/> Share</Button></div><p className="engagement-note">यी प्रतिक्रिया र views यस वेबसाइटका हुन्। Social platform counts are separate.</p><section className="comments"><h2>आफ्नो विचार राख्नुहोस् <span>{post.comments}</span></h2>{user?<form onSubmit={comment}><label htmlFor="comment">सम्मानपूर्ण संवाद गरौँ · Your comment</label><Textarea id="comment" value={body} onChange={e=>setBody(e.target.value)} placeholder="तपाईं के सोच्नुहुन्छ?" minLength={2} maxLength={1500} required/><Button type="submit" disabled={busy}>{busy?"Posting…":"टिप्पणी गर्नुहोस्"}<Send size={16}/></Button></form>:<div className="comment-signin"><p>कुराकानीमा सहभागी हुन Login गर्नुहोस्।</p><a href={`/login?next=/post/${id}`} className="btn">Sign in to comment</a></div>}{message&&<p role="status" className="form-message">{message}</p>}{comments.length?comments.map(c=><article className="comment" key={c.id}><span className="comment-avatar">{c.name.slice(0,1).toUpperCase()}</span><div><b>{c.name}</b><small>{dateLabel(c.created_at)}</small><p>{c.body}</p></div></article>):<p className="muted">पहिलो विचार तपाईंको हुन सक्छ। Be the first to comment.</p>}</section></article>}</main>}
