"use client";

import {usePathname} from "next/navigation";
import {createContext,useContext,useEffect,useState,type ReactNode} from "react";
import {ArrowUpRight,MapPin,Menu,X,LogOut,UserRound} from "@/lib/icons";
import type {Member} from "@/lib/models";
import {Button} from "@/components/ui/button";
type Session={user:Member|null;ready:boolean;error:string;retry:()=>void};
const SessionContext=createContext<Session>({user:null,ready:false,error:"",retry:()=>{}});
export const useSession=()=>useContext(SessionContext);
export async function api(path:string,options:RequestInit={}){
 try{
  const r=await fetch("/api/"+path,{...options,signal:options.signal||AbortSignal.timeout(15000),headers:{...(options.body instanceof FormData?{}:{"Content-Type":"application/json"}),...options.headers}});
  const type=r.headers.get("content-type")||"";
  if(!type.includes("application/json"))throw new Error("The service did not return a valid response. Please retry.");
  const data=await r.json() as any;
  if(!r.ok){const e=new Error(data.error||"Something went wrong") as Error&{status:number};e.status=r.status;throw e}
  return data;
 }catch(e){if(e instanceof Error&&(e.name==="TimeoutError"||e.name==="AbortError"))throw new Error("Loading took too long. Please retry.");throw e}
}
export default function SiteShell({children}:{children:ReactNode}){const path=usePathname();const[open,setOpen]=useState(false);const[user,setUser]=useState<Member|null>(null);const[ready,setReady]=useState(false);const[error,setError]=useState("");const[attempt,setAttempt]=useState(0);const[expires,setExpires]=useState<number|null>(null);
useEffect(()=>{let active=true;setReady(false);setError("");api("session",{method:"POST"}).then(d=>{if(!active)return;setUser(d.user);setExpires(d.user||d.previewUntil<=d.serverNow?null:Date.now()+(d.previewUntil-d.serverNow));setReady(true)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[attempt]);
useEffect(()=>{if(!ready||user||expires===null)return;const t=setTimeout(()=>{window.location.assign("/login?next="+encodeURIComponent(window.location.pathname))},Math.max(0,expires-Date.now()));return()=>clearTimeout(t)},[ready,user,expires,path]);
const nav=[["/","गृहपृष्ठ","Home"],["/videos","भिडियो","Videos"],["/gallery","ग्यालरी","Gallery"],["/blog","लेख र विचार","Blog"]];
return <SessionContext.Provider value={{user,ready,error,retry:()=>setAttempt(n=>n+1)}}><div className="site"><div className="topbar"><div className="wrap"><span><MapPin size={13}/> प्रसौनी, बारा · Nepal</span><span className="topbar-right">स्थानीय कथा। साझा आवाज। <a href="https://www.facebook.com/prasaunivoice" target="_blank" rel="noreferrer" aria-label="Prasauni Voice on Facebook"><b aria-hidden="true">f</b></a><a href="https://www.tiktok.com/@prasaunivoice" target="_blank" rel="noreferrer">TikTok ↗</a></span></div></div><header className="site-header"><div className="wrap header-inner"><a href="/" className="brand" aria-label="Prasauni Voice home"><span className="brand-mark">PV<span>●</span></span><span>प्रसौनी <b>Voice</b><small>PRASAUNI, NEPAL</small></span></a><nav aria-label="Main navigation" className="desktop-nav">{nav.map(([href,ne,en])=><a href={href} key={href} className={path===href?"active":""}>{ne}<small>{en}</small></a>)}</nav><div className="header-actions">{user?<><a href={user.admin?"/admin":"/login"} className="account-link"><UserRound size={17}/>{user.admin?"Admin":"Account"}</a><form action="/auth/signout" method="post"><button aria-label="Sign out" className="text-link"><LogOut size={17}/></button></form></>:<a href="/login" className="btn btn-small">जोडिनुहोस् <ArrowUpRight size={16}/></a>}<Button variant="ghost" size="icon" className="mobile-menu" aria-label="Toggle navigation" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</Button></div></div>{open&&<nav className="mobile-nav" aria-label="Mobile navigation">{nav.map(([href,ne,en])=><a key={href} href={href} onClick={()=>setOpen(false)}>{ne} <span>{en}</span></a>)}{user?.admin&&<a href="/admin">Admin dashboard</a>}</nav>}</header>{children}<footer className="site-footer"><div className="wrap footer-top"><div><a href="/" className="brand light"><span className="brand-mark">PV<span>●</span></span><span>प्रसौनी <b>Voice</b></span></a><p>आफ्नो ठाउँका कथा, आफ्नै मानिसको आवाज।<br/>Connecting Prasauni, one story at a time.</p></div><div><span className="footer-label">EXPLORE</span><a href="/">ताजा अपडेट</a><a href="/gallery">तस्बिर ग्यालरी</a><a href="/blog">लेख र विचार</a></div><div><span className="footer-label">STAY CONNECTED</span><a href="https://www.facebook.com/prasaunivoice" target="_blank" rel="noreferrer">Facebook <ArrowUpRight size={15}/></a><a href="https://www.tiktok.com/@prasaunivoice" target="_blank" rel="noreferrer">TikTok <ArrowUpRight size={15}/></a><a href="mailto:help.justenginer@gmail.com">सम्पर्क गर्नुहोस्</a></div></div><div className="wrap footer-bottom"><span>© {new Date().getFullYear()} Prasauni Voice · Made for Nepal</span><div><a href="/privacy">Privacy & guidelines</a><a href="/admin">Admin login</a></div></div></footer></div></SessionContext.Provider>}
