import { member } from "@/lib/server";
import { authConfigured } from "@/lib/supabase/server";
import { safeReturnTo } from "@/lib/auth-utils";

import {ArrowLeft,ArrowUpRight,ShieldCheck} from "lucide-react";
export const dynamic="force-dynamic";
export const metadata={title:"Login · सदस्य बन्नुहोस्"};
async function SignIn({returnTo}:{returnTo:string}){const u=await member();return u?<><p>You are signed in as {u.email}.</p><a href={returnTo} className="btn">Continue to Prasauni Voice <ArrowUpRight size={18}/></a><form action="/auth/signout" method="post"><button className="text-link">Sign out / Switch account</button></form></>:<><a href={"/auth/google?next="+encodeURIComponent(returnTo)} className="btn login-button">Continue with Google <ArrowUpRight size={18}/></a><p className="login-note">आफ्नो Google account बाट सुरक्षित Login गर्नुहोस्।<br/>No separate website password is needed.</p>{!authConfigured()&&<p role="status" className="error-box">Google sign-in setup is pending. Please try again after the site is connected.</p>}</>}
export default async function Page({searchParams}:{searchParams:Promise<{next?:string;error?:string;message?:string}>}){const p=await searchParams;const next=safeReturnTo(p.next);return <div className="login-layout"><div className="login-visual"><a href="/" className="brand light"><span className="brand-mark">PV<span>●</span></span><span>प्रसौनी <b>Voice</b></span></a><div><span className="eyebrow">FROM PRASAUNI. FOR OUR COMMUNITY.</span><h1>आफ्नो ठाउँ।<br/>आफ्नो आवाज।</h1><p>Stay connected to the stories that bring us together.</p></div><small>प्रसौनी गाउँपालिका, बारा · Nepal</small></div><main className="login-main"><a href="/" className="back-link"><ArrowLeft size={17}/> गृहपृष्ठमा फर्कनुहोस्</a><form action="/api/preview" method="post" className="login-preview"><button type="submit" className="text-link">फेरि ३० सेकेन्ड हेर्नुहोस् · Preview again</button></form><section><span className="eyebrow">WELCOME TO THE COMMUNITY</span><h2>जोडिनुहोस्,<br/>कुराकानी अगाडि बढाऔँ।</h2><p>पूरा पोस्ट हेर्न, मन पराउन र आफ्नो विचार राख्न Login गर्नुहोस्।</p>{p.error&&<p role="alert" className="error-box">{p.error==="setup"?"Google login is awaiting configuration.":"Google login could not be completed. Please try again."}</p>}{p.message&&<p role="status" className="success-box">{p.message}</p>}<SignIn returnTo={next}/><div className="login-trust"><ShieldCheck size={20}/><span>Your account identifies your likes and comments. Your email is never shown in public comments.</span></div><a href="/privacy">Privacy & community guidelines</a></section></main></div>}
